language: go
go_import_path: github.com/willie/groupcache

os: linux
dist: trusty
sudo: false

script:
  - go test ./...

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

cache:
  directories:
    - $GOPATH/pkg
